version: "3.1"
services:
  app:
    container_name: springapp
    image: springapp
    build: ./
    ports:
      - "8070:8070"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dadinos
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbforrevision
volumes:
  postgres-data: