name: Github Action Build App Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up and Build with Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: '3.6.3'

      - name: Build app
        run: mvn -f pom.xml --batch-mode --update-snapshots clean install -DskipTests

      - name: Run JUnit Tests
        run: mvn -f pom.xml --batch-mode --update-snapshots test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Images
        run: docker build -t abdiaoo/spring-boot-rest-api-jenkins:latest .

      - name: Display Docker Images
        run: docker images

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push abdiaoo/spring-boot-rest-api-jenkins:latest
